### ISSUE TITLE
lxml error when scraping variants from CDPH

### ISSUE THREAD

**Issue by stiles** [datadesk/california-coronavirus-scrapers#3]
The "[Variant totals in CA](https://github.com/datadesk/california-coronavirus-scrapers/actions/workflows/variant-toplines-ca.yaml
)" workflow fails when running the `variant-topline-ca` notebook. It's throwing an error because it can't find the lxml tool, which is needed by Pandas `read_html()` function. lxml is in the `Pipfile` and the notebook runs fine locally without errors. 

Any ideas? 

![Screen Shot 2021-04-17 at 3 50 56 PM](https://user-images.githubusercontent.com/232237/115128734-c55b4000-9f94-11eb-8fe2-8611a5ecbf07.png)

**Comment by palewire** [comment]
Out for a walk now in Chinatown. Will look in a bit

**Comment by palewire** [comment]
Looks like it's working now.
