### ISSUE TITLE
Vaccine zip code endpoint may change weekly

### ISSUE THREAD

**Issue by seangreene** [datadesk/california-coronavirus-scrapers#8]
We probably need to use beautifulsoup to find the url on that "Download All" button on [this page](https://data.chhs.ca.gov/dataset/covid-19-vaccine-progress-dashboard-data-by-zip-code)

**Comment by rdmurphy** [comment]
These pages have API endpoints we can use, probably no need scrape them.

https://data.chhs.ca.gov/api/3/action/package_show?id=covid-19-vaccine-progress-dashboard-data-by-zip-code

**Comment by stiles** [comment]
Now using the API to access the metadata about each of the weekly data urls and grab the latest one. 

![Screen Shot 2021-05-12 at 2 13 03 PM](https://user-images.githubusercontent.com/232237/118045090-57ecc600-b32c-11eb-8ee6-d9eda5011ea1.png)

**Comment by stiles** [comment]
Tested in the scraper and the processor. Looks OK.
